# ByeByeInventory by _NickV
# For support, please visit my Discord server: https://discord.gg/fGzb73sPmV

#### Dimensions
##
# To disable the plugin in a specific dimension, change the below settings.

enabled-in-overworld: true
enabled-in-nether: true
enabled-in-end: true

### Exclude the player hotbar
##
## Setting this to true will exclude any items in the player hotbar at the time of death
exclude-hotbar: false

### Exclude player armor
##
## Setting this to true will exclude any items stored in the armor inventory slots.
## This includes helmet, chestplate, leggings, and boot inventory slots.
exclude-armor: false

### Exclude player off-hand slot
##
## Setting this to true will exclude any item(s) stored in the off-hand inventory slot.
exclude-offhand: false

### Excluded item list
##
## Items in this list will not be removed upon death.
exclude-items: false
excluded-items-list:
  - COMMAND_BLOCK
  - EMERALD_ORE
  - DIAMOND

#### Log deaths to the console
##
## Will alert the console when a player has had their inventory voided by the plugin.
## The plugin will also print out how many items the player has lost.

log-death-to-console: true

### Broadcast message to server when a player's items are voided
##
## This message will not display if the player has an empty inventory.

display-message-to-server: false

### The message to send
message-to-server: '&8[!] &c%playername% &rdied in the %dimension% and lost %count% item(s)!'

### Display message to the player when their items are voided

display-message-to-player: true

## The message displayed to a player when their items are voided.
## This message will not display if the player has an empty inventory
message-to-player: 'You have died, and your inventory of &c%count% &ritem(s) have been destroyed.'

### Available keywords:
##
## %playername% -> Replaced with the player's username
## %newline% -> Creates a new line on the screen
## %count% -> Replaced with how many items were lost upon death
## %dimension% -> Replaced with the dimension (overworld, end, nether, or the name of a custom dimension)

### Updater
##
## Toggle the "There is an update available!" check

updater-enabled: true

### bStats plugin metrics

metrics-enabled: true